name: Generate Data
on: [push]
jobs:
    generate-data:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  persist-credentials: false
            #                 submodules: recursive
            - name: Checkout Data Repo
              uses: actions/checkout@v3
              with:
                  repository: elwina/Valorala2-data
                  path: ./public/Valorala2-data
                  persist-credentials: false

            - name: Setup Nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install pnpm
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: 6.31.0
            - name: Init Data
              run: |
                  pnpm install --frozen-lockfile
                  pnpm run init
            - name: Commit Data Files
              run: |
                  cd ./public/Valorala2-data
                  git checkout main
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git remote set-url origin https://github.com/elwina/Valorala2-data.git
                  git add .
                  git commit -m "generated"
                  git push -u origin main -force_with_lease
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  repository: elwina/Valorala2-data
                  github_token: ${{ secrets.PWT }}
                  github_url: https://github.com/elwina/Valorala2-data.git
                  branch: main
                  force_with_lease: true
