name: Generate Data
on:
    push:
        paths-ignore:
            - "public/"
jobs:
    generate-data:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  persist-credentials: false
            - name: Checkout Data Repo
              uses: actions/checkout@v3
              with:
                  repository: elwina/Valorala2-data
                  path: ./public/Valorala2-data
                  persist-credentials: false

            - name: Setup Nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install pnpm
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: 6.31.0
            - name: Submodule
              run: |
                  cd ./public/Valorala2-data
                  git checkout main
            - name: Init Data
              run: |
                  pnpm install --frozen-lockfile
                  pnpm run init
            - name: Commit Data Files
              run: |
                  cd ./public/Valorala2-data
                  git config --global user.email elwina@outlook.com
                  git config --global user.name elwina
                  git remote set-url origin https://elwina:${{ secrets.PWT }}@github.com/elwina/Valorala2-data.git
                  git add *
                  git commit -a -m "[skip actions]Generated data"
                  git push --force
            - name: Commit Main
              run: |
                  cd ../../
                  git checkout main
                  git submodule update
                  git remote set-url origin https://elwina:${{ secrets.PWT }}@github.com/elwina/Valorala2.git
                  git add *
                  git commit -a -m "[skip actions]Generated data"
                  git push origin main
